# Generated by Django 3.2.4 on 2021-06-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mysee',
            new_name='Mymodel',
        ),
    ]
