# Generated by Django 3.2.4 on 2021-06-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_mysee_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mymodel',
            new_name='Mysee',
        ),
    ]
